### ISSUE TITLE
The AVEDataset only contain 4097 videos

### ISSUE THREAD

**Issue by JackHenry1992** [YapengTian/AVE-ECCV18#11]
Thank you for sharing your perfect work.  
I have downloaded the AVEDataset by the provided [link](https://drive.google.com/file/d/1FjKwe79e0u96vdjIVwfRQ1V6SoDHe7kK/view).  After unzip, it only contains 4097 videos in the AVE folder. 
It will be really appreciated if you can check this again.

**Comment by YapengTian** [comment]
Since several videos have two event categories, they denote different samples but are the same videos. Please check the annotations.

**Comment by JackHenry1992** [comment]
Are the values in train_order.h5 corresponding to the line-num of Annotations.txt?

**Comment by YapengTian** [comment]
Yes! The file contains indices for training samples.
