### ISSUE TITLE
2 instruments in the video with 1 label

### ISSUE THREAD

**Issue by aaron-wu** [YapengTian/AVE-ECCV18#12]
HI, I find that in the "-PE8geTWt-g.mp4" file, there are 2 instruments (guitar and mandolin) in the video, but I only get the "mandolin" label in the annotation file.

**Comment by YapengTian** [comment]
There is an assumption is that most short videos only have one audio-visual event. It was annotated according to AudioSet sound class annotations. Since the video is in "mandolin", only the temporal boundary of "mandolin" is annotated. This is one limitation of the AVE dataset.
