### ISSUE TITLE
Questions about the ave dataset

### ISSUE THREAD

**Issue by FloretCat** [YapengTian/AVE-ECCV18#13]
Hi @YapengTian ,
Thanks for your great work first!

I wonder whether the number in file `train_order.h5` is the row index of the file `Annotations.txt`, which can be used to get the corresponding training data and labels.
Thanks for your reply~

**Comment by YapengTian** [comment]
Yes, the number denotes the row index of the Annotations.txt file.

**Comment by FloretCat** [comment]
Many thanks!
