### ISSUE TITLE
Only 4097 videos in Dataset?

### ISSUE THREAD

**Issue by varshanth** [YapengTian/AVE-ECCV18#14]
Hi,

Thanks for the dataset and the code. The drive link you have shared for the AVE Dataset only contains 4097 mp4 files whereas the paper mentions that 4143 videos are present. Can you please help me out regarding finding the other 46 videos?

Thanks

**Comment by YapengTian** [comment]
Thanks for your interest. Since several videos contain multiple labels, the 4097 videos are corresponding to 4143 annotated samples.

**Comment by varshanth** [comment]
Thank you!
