### ISSUE TITLE
Request for information on mapping h5 content to video ids

### ISSUE THREAD

**Issue by varshanth** [YapengTian/AVE-ECCV18#16]
Hi,

The labels in the h5 file are numerical while the Annotations.txt contain text only. Can you please let me know the mapping scheme? i.e. is Churchbell=label0 and Mandolin=label28 or is it in some other way?

Thanks!

**Comment by YapengTian** [comment]
![image](https://user-images.githubusercontent.com/12854360/84093636-cad91880-a9c8-11ea-8980-a83fc2e329ce.png)
Yes. But, we will plus one background class. So, the first 28 classes are in the order. The last one refers to the background class in our one-hot encoding.

**Comment by varshanth** [comment]
Perfect. Thanks!
