### ISSUE TITLE
Request to Provide VideoIDs for Noisy Dataset

### ISSUE THREAD

**Issue by varshanth** [YapengTian/AVE-ECCV18#17]
Hi,

Can you please provide the YouTube VideoIDs corresponding to the visual_feature_noisy.h5 ?

Thanks!

**Comment by YapengTian** [comment]
https://drive.google.com/file/d/1b9jIDLvo0uDacwWMbLwqJltp0BoJjy1f/view?usp=sharing 

Videos can be downloaded from this link: https://drive.google.com/file/d/1b9jIDLvo0uDacwWMbLwqJltp0BoJjy1f/view?usp=sharing.

**Comment by venuszhou** [comment]
@YapengTian Hi, I download the noisy data from the link you provided, but there is just noisy audio files? could you please provide the video files?

**Comment by YapengTian** [comment]
Hi. The videos can be found in this link: https://drive.google.com/file/d/1Iqba9lk_KOxxf5CFV33_XVoC5nuG8wiu/
