### ISSUE TITLE
Question about dataloader and visual_feature_extractor

### ISSUE THREAD

**Issue by JustinYuu** [YapengTian/AVE-ECCV18#19]
Hi,
  Recently I'm trying to use the file visual_feature_extractor.py to extract AVE dataset features using ResNet-152, but the visual features I got has a dim of  [4097, 10, 7, 7, 512], which is different to the dim of visual feature you provided([4143, 10, 7, 7, 512]) and thus caused an IndexError: index 4118 is out of bounds for axis 0 with size 4097.
  As the video number of AVE dataset is 4097 and one video might have multiple labels according to your reply in other issues, while in visual_feature_extractor.py, dim 0 is directly defined by the length of video dataset(line 31-35, line 72), I wonder if there remains other operations on video features extracted from visual_feature_extractor.py that hasn't been listed in current codes so as to change the shape of video features from [4097, 10, 7, 7, 512] to [4143, 10, 7, 7, 512].

**Comment by YapengTian** [comment]
Hi, 

Since there are videos with multiple labels, there are 4097 videos but 4143 annotations. The single event assumption is one limitation of the work. Thus, please use the order of annotation.txt file to extract features for each sample.  In this way, we can obtain 4143 video features.

**Comment by JustinYuu** [comment]
Thanks for your timely reponse! I'll try to use annotation.txt to extract features, thanks again for ur help!:)
