### ISSUE TITLE
How to understand heatmap?

### ISSUE THREAD

**Issue by asker-github** [YapengTian/AVE-ECCV18#21]
Hello, thank you for the paper you recommended. But I still have doubts about your project. I still want to raise it with you after thinking about it. I use your model and code. The results seem to show that the detection effect has nothing to do with sound, because I can detect faces without speaking, even with my back to the camera without speaking. Heatmap can always detect faces. I don't know if you have this kind of situation? What's the difference between the detected heatmap of talking and not speaking? How to understand it?

**Comment by YapengTian** [comment]
Since we did not perform any post-processing for the generated heatmaps, it will always produce non-zero attention maps even there is no audio-visual event. For your concern, I think the model indeed tries to localize sounding objects. A lot of results are shown in Fig. 5 and 6. Especially, in Fig. 6, we can see that if there is no audio-visual event in a frame, random
background regions will be attended (5th frame of the second example); otherwise, the
attention will focus on sounding sources. I do agree the model is not perfect since it has some failure examples and it will always generate attention maps for all video frames even we recognize there is no audio-visual event.

**Comment by YapengTian** [comment]
In addition, if you only care about active speakers in videos, you might learn a model using only speech and human data. I think much better results can be obtained.

**Comment by YapengTian** [comment]
For understanding the failure examples, the model selects the most related content in visual frames. Even there are no sound sources, the model still selects certain regions but it is incorrect. To address it, we might use the event localization results as gates. If there is no any audio-visual event, we can simply multiply 0 with attention weights.

**Comment by asker-github** [comment]
> For understanding the failure examples, the model selects the most related content in visual frames. Even there are no sound sources, the model still selects certain regions but it is incorrect. To address it, we might use the event localization results as gates. If there is no any audio-visual event, we can simply multiply 0 with attention weights.

I tried to use one video and multiple audio that didn't match, but the detection didn't change. OK, thank you very much for your answer.

**Comment by asker-github** [comment]
OK, thank you very much for your answer. I'll try again

> For understanding the failure examples, the model selects the most related content in visual frames. Even there are no sound sources, the model still selects certain regions but it is incorrect. To address it, we might use the event localization results as gates. If there is no any audio-visual event, we can simply multiply 0 with attention weights.

OK, thank you very much for your answer. I'll try again

**Comment by asker-github** [comment]
> For understanding the failure examples, the model selects the most related content in visual frames. Even there are no sound sources, the model still selects certain regions but it is incorrect. To address it, we might use the event localization results as gates. If there is no any audio-visual event, we can simply multiply 0 with attention weights.

I tried a variety of methods, but none of them worked well. Can you give me a hint? How to judge whether the audio is a specified category.
