### ISSUE TITLE
problem for generating audio-guided visual attention maps

### ISSUE THREAD

**Issue by zwr17** [YapengTian/AVE-ECCV18#22]
Hello, thank you for uploading the source code here. I tried to generate audio-guided visual attention maps for running attention_visualization.py. I used the provided dataset and feature, but there comes up a error on the line 116 "extract_frames[cc, :, :, :] = imgs[n] IndexError: list index out of range". I am solving this problem if you have any ideas.

**Comment by YapengTian** [comment]
Did you do any changes? You might print the index values to see why the indexerror happens.

**Comment by emontero1991** [comment]
I have same problem, could you tell me how to solve it.

**Comment by chocokassy** [comment]
I also encountered the same problem. After outputting, I found that frame_num.shape is (160,), and extract_frames is (301,224,224,3)
![2021-12-14 14-49-49屏幕截图](https://user-images.githubusercontent.com/32349968/145954777-4dcf993e-f129-4f30-8ef8-ea78b5d74daa.png)
