### ISSUE TITLE
如何获得4143组数据特征而不是4097组

### ISSUE THREAD

**Issue by tancoco** [YapengTian/AVE-ECCV18#30]
我想换个网络来提取视频中的视觉与音频特征，但在处理视频是发现只有4097个，不太清楚visual_feature.h5中怎么有4143个视觉数据（数据集备注信息中提到有些视频包含不同的音视频事件所以不是4143个视频），您能告诉我是怎么处理的吗？希望您回复，谢谢！

**Comment by YapengTian** [comment]
之前的数据里存在一个视频有不同audio-visual event的情况，所以有4143个标注但是视频数目略少于 4143。你可以依据https://github.com/YapengTian/AVE-ECCV18/blob/master/data/Annotations.txt 里的顺序来处理得到4143个feature。

**Comment by tancoco** [comment]
> 之前的数据里存在一个视频有不同audio-visual event的情况，所以有4143个标注但是视频数目略少于 4143。你可以依据https://github.com/YapengTian/AVE-ECCV18/blob/master/data/Annotations.txt 里的顺序来处理得到4143个feature。

嗯嗯嗯，明白了，谢谢您！！！
