### ISSUE TITLE
File visual_feature_vec.h5

### ISSUE THREAD

**Issue by tuffr5** [YapengTian/AVE-ECCV18#4]
Hello, thanks for your great work. I met the issue here:

with h5py.File('data/visual_feature_vec.h5', 'r') as hf:
    video_features = hf['avadataset'][:]

Is this visual_feature_vec.h5 just the same as visual_feature.h5?

Thanks.

**Comment by laohuijiadezhu** [comment]
Hi,
I have the same puestion. How to solve it?

**Comment by YapengTian** [comment]
The link (https://drive.google.com/file/d/1l-c8Kpr5SZ37h-NpL7o9u8YXBNVlX_Si/view) can be found in the readme (see the Cross-modality localization part).
