### ISSUE TITLE
How to use it for real time  when it takes 10s non-overlapping sequences?

### ISSUE THREAD

**Issue by anandhupvr** [YapengTian/AVE-ECCV18#6]
My understanding is input for this model is 10s video &audio sequence so how do i modify this for real-time?

**Comment by YapengTian** [comment]
Do you mean online real-time? Even though the training data is fixed 10s long, you can do testing second by second.

**Comment by anandhupvr** [comment]
So we get output evan from 1sec video and audio. And we don't need any sequence of 160video frames or 10s audio data right ?

**Comment by YapengTian** [comment]
Yes, you can still modify the code and run it since it is RNN sequential model, which can do inference on any lengths of sequence.

**Comment by anandhupvr** [comment]
yea ok thanks

**Comment by anandhupvr** [comment]
but the audio feature extraction network has fixed 1s audio input right? So then we need to wait for complete 1s to generate result for all 16 frames.
