### ISSUE TITLE
How to detach the audio file from the original mp4?

### ISSUE THREAD

**Issue by tymanman** [YapengTian/AVE-ECCV18#7]
I have downloaded the feature_extractor package,but in the audio extractor.py,there is a argument of "path of wav file".I don't know how to detach the audio channel for the whole video,please give me some instructions,thanks.

**Comment by YapengTian** [comment]
I used MoviePy to extract audio before. https://zulko.github.io/moviepy/getting_started/audioclips.html

**Comment by tymanman** [comment]
Thanks a lot.
